### ISSUE TITLE
Question about unlabeled data

### ISSUE THREAD

**Issue by johnson111788** [LLYXC/OXnet#3]
Hi 

Thanks for your excellent work. I am applying your code to my dataset with one category, that is, the image will be either positive  (with lesions) or negative (without a lesion).

I would like to know if should I deem these negative images as unlabeled data or abandon these negative images during training.

Best, 
Johnson

**Comment by johnson111788** [comment]
By the way, there are some bugs in train_retinanet.py during evaluation, including
1. missing augment `pure_retina' for forward() in coco_eval.py
2. wrong `coco_eval.stats' indexing by `metric_names[i]'

**Comment by LLYXC** [comment]
Hi Johnson,

Thanks for your interest. I think you can try the following options:
1. If you abandoned the negative images, then should use the current version. As I previously did work on multi-label problems, there won't be too many images abandoned, but if you have many negative images, I would suggest you try option 2 or 3;
2. If you treat the negative images as unlabeled data, you might gain more supervision from the consistency loss, and there would be some performance gain. The risk is that you might likely have more false positives;
3. You can also modify the loss so that the supervised retinanet loss will still function for the negative images, and from my experience, you will have less false positives.

Also, many thanks for pointing out the flaws! I will upgrade the code later.

Best,
Luyang
